server:
  port: 9090


#---------------------H2 DB config----------------------
spring:
  datasource:
    url: jdbc:h2:mem:schedular
    #url: jdbc:h2:mem:file:D:/h2-db/data
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      setting:
        trace: false
        web-allow-others: false
